### ISSUE TITLE
How to edit the Isomemo databases?

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-data#1]
Hi @wahani , these are more discussion and maybe suggestions we can give to @isomemo Ricardo concerning the Database edits. Currently we have 4 databases: 
![image](https://user-images.githubusercontent.com/73887426/160804330-1aab6373-30a2-4648-b139-61fc4123bded.png)

Because for each new database we want to add database into the API, we have to define the fields, how much will this take? will take a long time.? we will need some more advice from you whether this is possible to give Ricardo the ability to make additions to the database by himself so that we don't have to spend a long time defining the fields and handle the bulk of the work. Maybe we just give me a hidden env. credentials file?

**Comment by arunge** [comment]
There is a documentation (that was written by @aneudecker) on how to add new databases to the isomemo app. The whole set up was documented in [this ticket](https://github.com/INWT/mpi-iso-app/issues/234).

@isomemo The documentation contains links that point to the old repository. Of course, we must at least update those links such that they point to our current repository here.

Additionally, the names of some branches changed during migration. That means, the following part in the documentation needs to be updated:

> The package is automatically created and put into a docker image when pushing changes to the master or depl branch. The version from the master branch will be used for the testapi and the beta version of the isomemo app (https://isomemoapp.com/app/iso-memo-app-beta). The version from the depl branch will be used for the production api and the regular version of the app.
> All automatic processes (creation of docker images, updating data, backing up database) is done by Jenkins (https://isomemodb.com/jenkins/)
> 

For this, I will need advice of @wahani about the current set up.

@isomemo What I allready found is the .csv that defines the mapping which you mentioned in a previous meeting. Could you confirm that this is the correct csv: https://github.com/Pandora-IsoMemo/iso-data/blob/main/inst/mapping/Field_Mapping.csv ?

There remains to find a solution for potential credentials of new databases. Since the new repository is public now, there is no way of adding them here.

I will discuss options with @wahani , and we will return to you again.

**Comment by arunge** [comment]
note for me:
- update draft with smth. like here: 
https://github.com/Pandora-IsoMemo/iso-data/blob/408a6148c866fbfaa2dd1e522369b3f4d4d49af2/R/00-settings.R#L1-L10
- add variables also here: https://github.com/Pandora-IsoMemo/iso-data/blob/a513226da95e31c5ba9ca7834f2ce37ba0da260a/.gitignore#L4

**Comment by jroachell15** [comment]
@wahani @arunge 
@isomemo 

We will arrange a meeting to see how we can help add new databases into the Iso-Memo App (will go into new contract)
- improve the language and documentation
- update the links and scripts
- need groups of databases, which adds one more layer on top of the existing layer
- need to talk about the passwords and credentials

**Comment by jroachell15** [comment]
@wahani any comments here?

**Comment by arunge** [comment]
Under review now.

**Comment by isomemo** [comment]
I think that that the question is different! As owner of this system, of course I can do any edit. To avoid potential mistakes that I could introduce it is fine for now to restrict access. However, when it comes to the databases being shown in the IsoMemo app this is controlled via a script that I can edit. Whenever I edit this there is a quasi automatic update ( a few additional steps may be required) to the databases being listed (plus I can also edit other features such as category/field selections). This was a task implemented by Andreas. In the future version of this script there will be one level above that of individual databases. Again, I will be able to edit this via such script.

**Comment by arunge** [comment]
@isomemo There was another issue here. The [past proccess](https://github.com/Pandora-IsoMemo/iso-data/blob/main/README.md) of adding new data sources was not sufficient anymore since the transfer to the new repo. Now, one would need to adjust more files and take care of files to be uploaded to github and the one with credentials that should not. Doing this by hand is too prone to errors. Thats why @wahani and me decided that it is best to have a function that prepares the three different scripts, and an entry in the `.gitignore` that prevents the file `.Renviron` with credentails to be uploaded to github.

Currently, you can find the [new description](https://github.com/Pandora-IsoMemo/iso-data/blob/beta/README.md) and the new functions on the beta version of this package. To test them you need to locally download the package, switch to the beta branch (e.g. via RStudio) and follow the description in the readme. If you have any questions please feel free to ask.

The task with the "level above" is not part of this issue here. This we still need to develope.

**Comment by isomemo** [comment]
@isomemo this was part of the original specification and is fundamental. We only started using local files out of convenience for testing pourposes.

**Comment by arunge** [comment]
The [README](https://github.com/Pandora-IsoMemo/iso-data/blob/beta/README.md) must be updated after we added the new higher level above within #4. While developing this feature I will check if urls can be used as sources. If not, I will add this feature within #4.

Until #4 is finished I will put this ticket on-hold.

**Comment by isomemo** [comment]
@arunge Ok on hold!

**Comment by arunge** [comment]
Adding new sources will be tested and discussed in another ticket:
- https://github.com/Pandora-IsoMemo/iso-data/issues/12

I am closing here.
